r""" Stage (iii) of the paper pipeline: build every table and figure from results/ and copy them into
writing/Paper.

Run:  .venv\Scripts\python.exe python\paper\build.py                 build everything buildable
      ... --only ArgentinaUniversal ARG_CRRA_LOG                     a subset
      ... --no-copy                                                  write results/paper only
      ... --list                                                     what is buildable and what is not
      ... --map                                                      rewrite the output map in REPLICATION.md
      ... --site                                                     write the online appendix from
                                                                     results/paper (onlineAppendix.build)

This stage imports NO model code and unpickles nothing. It reads csv, writes tex and pdf, and takes
seconds -- which is what makes it safe to re-run after every edit to a caption or a rounding rule. The
expensive work belongs to stages (i) and (ii), whose output in results/ is the record.

An output whose inputs are missing is REPORTED AND SKIPPED, never partially written: an experiment that
has not been run must not be able to look like a table that has.

WHERE THINGS LAND. Every output is written to results/paper/ first and then copied into writing/Paper/
(--no-copy stops at the first step), except the online appendix's own exhibits (ONLINE_ONLY), which stay
in results/paper/. The first time a copy would overwrite a file that does not carry
this pipeline's banner -- i.e. the hand-written version still in the repo -- that file is preserved
under results/paper/superseded/ and the takeover is announced. Superseded content never stays beside
live content (notes/crossCuttingFindings.md #8).
"""
import os, sys, argparse, shutil, datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config as C
import datasets as D
import tables, figures
import tablesUS, figuresUS
import oecdFigure1
import tablesOA, figuresOA

BANNER_MARK = 'GENERATED by python/paper/build.py'

# The US arm's builders each produce a headline table or figure AND its robustness twin, differing only
# in which calibration variant they read. The headline keeps the plain name, filename and tex label the
# draft already cites; the twin's carry the variant they contain (config.variantSuffix). ALT is the
# variant that is not leading, so flipping config.US['commonX'] swaps which numbers are in the headline
# without renaming a single output the paper inputs -- only the twins' filenames follow the flip.
ALT = not C.US['commonX']
ALTTAG = C.variantSuffix(ALT)


def _variants(name, fn, folder, ext = 'tex', arm = 'US'):
    """ {headline name: entry, twin name: entry} for one US or Argentina builder (`arm`). """
    kind = 'table' if ext == 'tex' else 'figure'
    alt = not (C.US if arm == 'US' else C.ARG)['commonX']
    tag = C.variantSuffix(alt, arm)
    return {name: (kind, fn, '{}/{}.{}'.format(folder, name, ext)),
            name + tag: (kind, (lambda f = fn, a = alt: f(commonX = a)),
                         '{}/{}{}.{}'.format(folder, name, tag, ext))}


# name -> (kind, builder, destination relative to writing/Paper)
OUTPUTS = {
    # --- Argentina. Each line registers the headline (config.ARG['commonX']) and its variant twin. ---
    **_variants('ArgentinaCalibration', tables.argentinaCalibration, 'Tables', arm = 'ARG'),
    **_variants('ArgentinaUniversal',   tables.argentinaUniversal,   'Tables', arm = 'ARG'),
    **_variants('Argentina_funcOfRho',  tables.argentinaFuncOfRho,   'Tables', arm = 'ARG'),
    **_variants('ArgentinaReformByRho', tables.argentinaReformByRho, 'Tables', arm = 'ARG'),
    **_variants('ARG_LOG_FourInOne',    figures.argLogFourInOne,     'Figs', ext = 'pdf', arm = 'ARG'),
    **_variants('ARG_CRRA_LOG',         figures.argCrraLog,          'Figs', ext = 'pdf', arm = 'ARG'),
    # --- US / France / UK. Each line registers two outputs: the headline and its variant twin. ---
    **_variants('USUKFRCalibration',        tablesUS.usukfrCalibration,        'Tables'),
    **_variants('US_householdheterogeneity', tablesUS.usHouseholdHeterogeneity, 'Tables'),
    **_variants('FR_householdheterogeneity', tablesUS.frHouseholdHeterogeneity, 'Tables'),
    **_variants('UK_householdheterogeneity', tablesUS.ukHouseholdHeterogeneity, 'Tables'),
    **_variants('US_PensChars',             tablesUS.usPensChars,              'Tables'),
    **_variants('US_Ageing',                tablesUS.usAgeing,                 'Tables'),
    **_variants('US_OtherShocks',           tablesUS.usOtherShocks,            'Tables'),
    **_variants('US_CRRA_PensChars',        tablesUS.usCrraPensChars,          'Tables'),
    **_variants('US_CRRA_Ageing',           tablesUS.usCrraAgeing,             'Tables'),
    **_variants('US_CRRA_OtherShocks',      tablesUS.usCrraOtherShocks,        'Tables'),
    **_variants('US_overview',              figuresUS.usOverview,        'Figs', ext = 'pdf'),
    # --- The UK exercise: French characteristics on the UK, France cut at the UK's groups (config.US['ukHost']).
    **_variants('FRUK_householdheterogeneity', tablesUS.frukHouseholdHeterogeneity, 'Tables'),
    **_variants('UK_OtherShocks',           tablesUS.ukOtherShocks,            'Tables'),
    **_variants('UK_CRRA_OtherShocks',      tablesUS.ukCrraOtherShocks,        'Tables'),
    **_variants('UK_CRRA_PensChars',        tablesUS.ukCrraPensChars,          'Tables'),
    **_variants('UK_CRRA_Ageing',           tablesUS.ukCrraAgeing,             'Tables'),
    **_variants('UKUS_householdheterogeneity', tablesUS.ukusHouseholdHeterogeneity, 'Tables'),
    **_variants('UKUS_French',              figuresUS.ukusFrench,        'Figs', ext = 'pdf'),
    # --- Endogenous system characteristics (app:ESC). Headline variant only -- see paper/README.md. ---
    'US_ESC_overview':        ('figure', figuresUS.escOverview,       'Figs/US_ESC_overview.pdf'),
    'US_ESC_Calibration':     ('table', tablesUS.escCalibrationTable, 'Tables/US_ESC_Calibration.tex'),
    'US_ESC_Ageing':          ('table', tablesUS.escAgeing,           'Tables/US_ESC_Ageing.tex'),
    'US_ESC_IncomeDistr':     ('table', tablesUS.escIncomeDistr,      'Tables/US_ESC_IncomeDistr.tex'),
    'US_ESC_Voting':          ('table', tablesUS.escVoting,           'Tables/US_ESC_Voting.tex'),
    'US_ESC_FrenchAll':       ('table', tablesUS.escFrenchAll,        'Tables/US_ESC_FrenchAll.tex'),
    'US_ESC_Summary':         ('table', tablesUS.escSummary,          'Tables/US_ESC_Summary.tex'),
    # The cross-country test (app:US:ukESC): the UK, France and the UK at US income groups under the US
    # parameter, and their own. tablesUS.ukEscCalibrationTable, the UK-only table it replaces, stays
    # callable on the comparison arm's rows but is not an output.
    'US_ESC_Country':         ('table', tablesUS.escCountryTable,     'Tables/US_ESC_Country.tex'),
    # The previous cost specification (config.US['esc']['comparisonSpec']) as one appendix table.
    'US_ESC_ScaleWedge':      ('table', tablesUS.escScaleWedge,       'Tables/US_ESC_ScaleWedge.tex'),
    # France's characteristics on the UK at the UK's own cost parameter (app:UKUS), and the US-UK figure.
    'UK_ESC_IncomeDistr':     ('table', tablesUS.ukEscIncomeDistr,    'Tables/UK_ESC_IncomeDistr.tex'),
    'UK_ESC_Voting':          ('table', tablesUS.ukEscVoting,         'Tables/UK_ESC_Voting.tex'),
    'UK_ESC_FrenchAll':       ('table', tablesUS.ukEscFrenchAll,      'Tables/UK_ESC_FrenchAll.tex'),
    'UKUS_ESC_French':        ('figure', figuresUS.ukusEscFrench,     'Figs/UKUS_ESC_French.pdf'),
    # Figure 1 (fig:US:OECDdata) from stage (0)'s data/oecdFigure1.csv; also writes oecdCorrelations.csv.
    'OECDdata':               ('figure', oecdFigure1.figure,          'Figs/OECDdata.pdf'),
    # The robustness map (app:robustness, and the online appendix's front page).
    'RobustnessMap':          ('figure', figuresUS.robustnessMap,     'Figs/RobustnessMap.pdf'),
    # --- The online appendix's own exhibits (tablesOA, figuresOA), all in ONLINE_ONLY. OECD_Correlations
    # after OECDdata, whose build writes its input. ---
    'OECD_Countries':         ('table', tablesOA.oecdCountries,       'Tables/OECD_Countries.tex'),
    'OECD_Sources':           ('table', tablesOA.oecdSources,         'Tables/OECD_Sources.tex'),
    'OECD_Correlations':      ('table', tablesOA.oecdCorrelations,    'Tables/OECD_Correlations.tex'),
    **_variants('ArgentinaReformPath',  tablesOA.argentinaReformPath,  'Tables', arm = 'ARG'),
    **_variants('ARG_RhoGridTable',     tablesOA.argRhoGridTable,      'Tables', arm = 'ARG'),
    **_variants('ARG_RhoGrid',          figuresOA.argRhoGrid,          'Figs', ext = 'pdf', arm = 'ARG'),
    **_variants('OECD_RhoGridTable',    tablesOA.oecdRhoGridTable,     'Tables'),
    **_variants('OECD_RhoGrid',         figuresOA.oecdRhoGrid,         'Figs', ext = 'pdf'),
    'ESC_Path':               ('figure', figuresOA.escPath,           'Figs/ESC_Path.pdf'),
    'ESC_PathTable':          ('table', tablesOA.escPathTable,        'Tables/ESC_PathTable.tex'),
    'ESC_Xi':                 ('table', tablesOA.escXi,               'Tables/ESC_Xi.tex'),
    'ESC_Timing':             ('table', tablesOA.escTiming,           'Tables/ESC_Timing.tex'),
    'NUM_Stationary':         ('table', tablesOA.numStationary,       'Tables/NUM_Stationary.tex'),
    'NUM_Selection':          ('table', tablesOA.numSelection,        'Tables/NUM_Selection.tex'),
}

# Registered outputs that belong to the online appendix alone: built into results/paper, never copied
# into writing/Paper.
_ARGALT = C.variantSuffix(not C.ARG['commonX'], 'ARG')
ONLINE_ONLY = ({'ArgentinaReformByRho', 'ArgentinaReformByRho' + _ARGALT,
                'UK_CRRA_PensChars', 'UK_CRRA_PensChars' + ALTTAG, 'UK_CRRA_Ageing', 'UK_CRRA_Ageing' + ALTTAG,
                'OECD_Countries', 'OECD_Sources', 'OECD_Correlations',
                'ESC_Path', 'ESC_PathTable', 'ESC_Xi', 'ESC_Timing', 'NUM_Stationary', 'NUM_Selection'}
               | {n + t for n in ('ArgentinaReformPath', 'ARG_RhoGridTable', 'ARG_RhoGrid') for t in ('', _ARGALT)}
               | {n + t for n in ('OECD_RhoGridTable', 'OECD_RhoGrid') for t in ('', ALTTAG)})


def _copy(src, dest, report):
    """ Copy one built file into writing/Paper, preserving a hand-written predecessor exactly once. """
    os.makedirs(os.path.dirname(dest), exist_ok = True)
    if os.path.exists(dest) and dest.endswith('.tex'):
        with open(dest, encoding = 'utf-8') as f:
            head = f.read(4096)
        if BANNER_MARK not in head:
            keep = os.path.join(C.PAPERDIR, 'superseded', os.path.basename(dest))
            os.makedirs(os.path.dirname(keep), exist_ok = True)
            shutil.copy2(dest, keep)
            report.append('  kept the hand-written {} as {}'.format(
                os.path.basename(dest), os.path.relpath(keep, C.REPO)))
    shutil.copy2(src, dest)


def build(name, copy = True, report = None):
    kind, fn, rel = OUTPUTS[name]
    report = [] if report is None else report
    if kind == 'table':
        text = fn()
        os.makedirs(os.path.join(C.PAPERDIR, 'Tables'), exist_ok = True)
        src = os.path.join(C.PAPERDIR, 'Tables', os.path.basename(rel))
        with open(src, 'w', encoding = 'utf-8') as f:
            f.write(text)
        built = [src]
    else:
        built = fn()
        src = [p for p in built if p.endswith('.pdf')][0]
    if copy and name not in ONLINE_ONLY:
        _copy(src, os.path.join(C.PAPERTEX, rel), report)
    return built, rel


MAP_FILE = os.path.join(C.REPO, 'REPLICATION.md')
MAP_BEGIN, MAP_END = '<!-- outputs:begin -->', '<!-- outputs:end -->'


def _traceInputs(fn):
    """ Run one builder with pandas' file readers wrapped, and return the repo-relative paths it read.
    Every csv a builder uses goes through pd.read_csv, so the trace is the builder's input list; a figure
    builder also writes its files to results/paper, as --list does. """
    import pandas as pd
    seen, orig = [], (pd.read_csv, pd.read_excel)

    def wrap(f):
        def g(path, *a, **k):
            if isinstance(path, (str, os.PathLike)):
                seen.append(os.path.abspath(os.fspath(path)))
            return f(path, *a, **k)
        return g
    pd.read_csv, pd.read_excel = wrap(orig[0]), wrap(orig[1])
    try:
        fn()
    finally:
        pd.read_csv, pd.read_excel = orig
    root = os.path.abspath(C.REPO)
    return sorted({os.path.relpath(p, root).replace(os.sep, '/') for p in seen if p.startswith(root)})


def _compress(paths):
    """ Paths that differ only in a rho value collapse into one `rho*` pattern with a file count. """
    import re
    groups = {}
    for p in paths:
        groups.setdefault(re.sub(r'rho\d+\.\d+', 'rho*', p), []).append(p)
    return ', '.join('`{}`'.format(pat) + (' ({} files)'.format(len(ps)) if len(ps) > 1 else '')
                     for pat, ps in groups.items())


def _usedIn():
    """ {path as the paper's tex writes it: [tex files, relative to writing/Paper, that input it]}. """
    import re
    uses = {}
    for d, dirs, files in os.walk(C.PAPERTEX):
        dirs[:] = [x for x in dirs if x not in ('Tables', 'exports')]
        for f in files:
            if not f.endswith('.tex'):
                continue
            p = os.path.join(d, f)
            with open(p, encoding = 'utf-8', errors = 'replace') as fh:
                text = fh.read()
            rel = os.path.relpath(p, C.PAPERTEX).replace(os.sep, '/')
            for m in re.finditer(r'\\(?:input|includegraphics)\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}', text):
                uses.setdefault(m.group(1).strip(), []).append(rel)
    return uses


def writeMap():
    """ The output map of REPLICATION.md: one row per registered output, with the files it reads (traced,
    not declared) and the tex files that input it. Rewritten between MAP_BEGIN/MAP_END; printed when the
    markers are missing. """
    uses = _usedIn()
    rows = ['| Output | Kind | File in `writing/Paper` | Reads | Input by |', '|---|---|---|---|---|']
    for name, (kind, fn, rel) in OUTPUTS.items():
        try:
            reads = _compress(_traceInputs(fn))
        except D.MissingInput as e:
            reads = 'BLOCKED: {}'.format(e)
        where = uses.get(rel, []) + uses.get(os.path.splitext(rel)[0], [])
        if name in ONLINE_ONLY:
            rows.append('| `{}` | {} | online appendix only | {} | -- |'.format(name, kind, reads))
            continue
        rows.append('| `{}` | {} | `{}` | {} | {} |'.format(
            name, kind, rel, reads, ', '.join('`{}`'.format(w) for w in where) or 'online appendix'))
    block = ('{}\n{} outputs, generated by `python\\paper\\build.py --map` on {}. Reads are traced at build '
             'time, `rho*` standing for the files of a rho grid. Every output is shown in the online appendix '
             '(`writing/OnlineAppendix`); "online appendix" marks one the paper does not input, and "online '
             'appendix only" one that is not copied into `writing/Paper` at all.\n\n{}\n{}'
             .format(MAP_BEGIN, len(OUTPUTS), datetime.date.today().isoformat(), '\n'.join(rows), MAP_END))
    if not os.path.exists(MAP_FILE):
        print(block)
        return
    with open(MAP_FILE, encoding = 'utf-8') as f:
        text = f.read()
    i, j = text.find(MAP_BEGIN), text.find(MAP_END)
    if i < 0 or j < 0:
        print(block)
        return
    with open(MAP_FILE, 'w', encoding = 'utf-8', newline = '\n') as f:
        f.write(text[:i] + block + text[j + len(MAP_END):])
    print('map written: {} ({} outputs)'.format(os.path.relpath(MAP_FILE, C.REPO), len(OUTPUTS)))


def main():
    p = argparse.ArgumentParser(description = __doc__.split('\n')[1])
    p.add_argument('--only', nargs = '+', choices = list(OUTPUTS), default = list(OUTPUTS))
    p.add_argument('--copy', dest = 'copy', action = 'store_true', default = True,
                   help = 'copy into writing/Paper (the default)')
    p.add_argument('--no-copy', dest = 'copy', action = 'store_false',
                   help = 'write results/paper only, leaving writing/Paper untouched')
    p.add_argument('--list', action = 'store_true', help = 'report buildability and exit')
    p.add_argument('--map', action = 'store_true', help = 'rewrite the output map in REPLICATION.md and exit')
    p.add_argument('--site', action = 'store_true',
                   help = 'write the online appendix from results/paper (onlineAppendix.build) and exit')
    a = p.parse_args()
    if a.map:
        writeMap()
        return
    if a.site:
        try:
            import onlineAppendix          # lazily: the paper build never needs it
        except ModuleNotFoundError as e:
            if e.name != 'onlineAppendix':
                raise
            print('--site: python/paper/onlineAppendix.py is missing; the online appendix cannot be built.')
            sys.exit(1)
        onlineAppendix.build()
        return

    built, skipped, report = [], [], []
    for name in a.only:
        kind, fn, rel = OUTPUTS[name]
        if a.list:
            try:
                fn()                      # cheap; the loaders raise before any real work
                print('{:<22} {:<7} OK'.format(name, kind))
            except D.MissingInput as e:
                print('{:<22} {:<7} BLOCKED -- {}'.format(name, kind, e))
            continue
        try:
            paths, rel = build(name, a.copy, report)
            built.append((name, rel, paths))
            print('built  {:<22} -> {}'.format(name, rel if a.copy and name not in ONLINE_ONLY else
                                               os.path.relpath(paths[0], C.REPO)))
        except D.MissingInput as e:
            skipped.append((name, str(e)))
            print('SKIP   {:<22} {}'.format(name, e))

    if a.list:
        return
    for line in report:
        print(line)
    print('\n{} built, {} skipped{}.'.format(len(built), len(skipped),
                                             '' if a.copy else ' (not copied: --no-copy)'))
    if skipped:
        print('Run the missing experiments with one of:')
        print('  .venv\\Scripts\\python.exe python\\paper\\runShocks.py      (Argentina)')
        print('  .venv\\Scripts\\python.exe python\\paper\\runShocksUS.py    (US / France / UK)')
        print('...and if a calibration is what is missing, the matching runCalibration*.py first.')
        for name, why in skipped:
            print('  {:<22} {}'.format(name, why))


if __name__ == '__main__':
    main()
