r""" Stage (iii) of the paper pipeline: build every table and figure from results/ and copy them into
writing/Paper.

Run:  .venv\Scripts\python.exe python\paper\build.py                 build everything buildable
      ... --only ArgentinaUniversal ARG_CRRA_LOG                     a subset
      ... --no-copy                                                  write results/paper only
      ... --list                                                     what is buildable and what is not

This stage imports NO model code and unpickles nothing. It reads csv, writes tex and pdf, and takes
seconds -- which is what makes it safe to re-run after every edit to a caption or a rounding rule. The
expensive work belongs to stages (i) and (ii), whose output in results/ is the record.

An output whose inputs are missing is REPORTED AND SKIPPED, never partially written: an experiment that
has not been run must not be able to look like a table that has.

WHERE THINGS LAND. Every output is written to results/paper/ first and then copied into writing/Paper/
(--no-copy stops at the first step). The first time a copy would overwrite a file that does not carry
this pipeline's banner -- i.e. the hand-written version still in the repo -- that file is preserved
under results/paper/superseded/ and the takeover is announced. Superseded content never stays beside
live content (notes/crossCuttingFindings.md #8).
"""
import os, sys, argparse, shutil, datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config as C
import datasets as D
import tables, figures
import tablesUS, figuresUS

BANNER_MARK = 'GENERATED by python/paper/build.py'

# The US arm's builders each produce a headline table or figure AND its robustness twin, differing only
# in which calibration variant they read. The headline keeps the plain name, filename and tex label the
# draft already cites; the twin's carry the variant they contain (config.variantSuffix). ALT is the
# variant that is not leading, so flipping config.US['commonX'] swaps which numbers are in the headline
# without renaming a single output the paper inputs -- only the twins' filenames follow the flip.
ALT = not C.US['commonX']
ALTTAG = C.variantSuffix(ALT)


def _variants(name, fn, folder, ext = 'tex', arm = 'US'):
    """ {headline name: entry, twin name: entry} for one US or Argentina builder (`arm`). """
    kind = 'table' if ext == 'tex' else 'figure'
    alt = not (C.US if arm == 'US' else C.ARG)['commonX']
    tag = C.variantSuffix(alt, arm)
    return {name: (kind, fn, '{}/{}.{}'.format(folder, name, ext)),
            name + tag: (kind, (lambda f = fn, a = alt: f(commonX = a)),
                         '{}/{}{}.{}'.format(folder, name, tag, ext))}


# name -> (kind, builder, destination relative to writing/Paper)
OUTPUTS = {
    # --- Argentina. Each line registers the headline (config.ARG['commonX']) and its variant twin. ---
    **_variants('ArgentinaCalibration', tables.argentinaCalibration, 'Tables', arm = 'ARG'),
    **_variants('ArgentinaUniversal',   tables.argentinaUniversal,   'Tables', arm = 'ARG'),
    **_variants('Argentina_funcOfRho',  tables.argentinaFuncOfRho,   'Tables', arm = 'ARG'),
    **_variants('ARG_LOG_FourInOne',    figures.argLogFourInOne,     'Figs', ext = 'pdf', arm = 'ARG'),
    **_variants('ARG_CRRA_LOG',         figures.argCrraLog,          'Figs', ext = 'pdf', arm = 'ARG'),
    # --- US / France / UK. Each line registers two outputs: the headline and its variant twin. ---
    **_variants('USUKFRCalibration',        tablesUS.usukfrCalibration,        'Tables'),
    **_variants('US_householdheterogeneity', tablesUS.usHouseholdHeterogeneity, 'Tables'),
    **_variants('FR_householdheterogeneity', tablesUS.frHouseholdHeterogeneity, 'Tables'),
    **_variants('UK_householdheterogeneity', tablesUS.ukHouseholdHeterogeneity, 'Tables'),
    **_variants('US_PensChars',             tablesUS.usPensChars,              'Tables'),
    **_variants('US_Ageing',                tablesUS.usAgeing,                 'Tables'),
    **_variants('US_OtherShocks',           tablesUS.usOtherShocks,            'Tables'),
    **_variants('US_CRRA_PensChars',        tablesUS.usCrraPensChars,          'Tables'),
    **_variants('US_CRRA_Ageing',           tablesUS.usCrraAgeing,             'Tables'),
    **_variants('US_CRRA_OtherShocks',      tablesUS.usCrraOtherShocks,        'Tables'),
    **_variants('US_overview',              figuresUS.usOverview,        'Figs', ext = 'pdf'),
    # --- Endogenous system characteristics (app:ESC). Headline variant only -- see paper/README.md. ---
    'US_ESC_overview':        ('figure', figuresUS.escOverview,       'Figs/US_ESC_overview.pdf'),
    'US_ESC_Calibration':     ('table', tablesUS.escCalibrationTable, 'Tables/US_ESC_Calibration.tex'),
    'US_ESC_Ageing':          ('table', tablesUS.escAgeing,           'Tables/US_ESC_Ageing.tex'),
    'US_ESC_IncomeDistr':     ('table', tablesUS.escIncomeDistr,      'Tables/US_ESC_IncomeDistr.tex'),
    'US_ESC_Voting':          ('table', tablesUS.escVoting,           'Tables/US_ESC_Voting.tex'),
    'US_ESC_FrenchAll':       ('table', tablesUS.escFrenchAll,        'Tables/US_ESC_FrenchAll.tex'),
    'UK_ESC_Calibration':     ('table', tablesUS.ukEscCalibrationTable, 'Tables/UK_ESC_Calibration.tex'),
}


def _copy(src, dest, report):
    """ Copy one built file into writing/Paper, preserving a hand-written predecessor exactly once. """
    os.makedirs(os.path.dirname(dest), exist_ok = True)
    if os.path.exists(dest) and dest.endswith('.tex'):
        with open(dest, encoding = 'utf-8') as f:
            head = f.read(4096)
        if BANNER_MARK not in head:
            keep = os.path.join(C.PAPERDIR, 'superseded', os.path.basename(dest))
            os.makedirs(os.path.dirname(keep), exist_ok = True)
            shutil.copy2(dest, keep)
            report.append('  kept the hand-written {} as {}'.format(
                os.path.basename(dest), os.path.relpath(keep, C.REPO)))
    shutil.copy2(src, dest)


def build(name, copy = True, report = None):
    kind, fn, rel = OUTPUTS[name]
    report = [] if report is None else report
    if kind == 'table':
        text = fn()
        os.makedirs(os.path.join(C.PAPERDIR, 'Tables'), exist_ok = True)
        src = os.path.join(C.PAPERDIR, 'Tables', os.path.basename(rel))
        with open(src, 'w', encoding = 'utf-8') as f:
            f.write(text)
        built = [src]
    else:
        built = fn()
        src = [p for p in built if p.endswith('.pdf')][0]
    if copy:
        _copy(src, os.path.join(C.PAPERTEX, rel), report)
    return built, rel


def main():
    p = argparse.ArgumentParser(description = __doc__.split('\n')[1])
    p.add_argument('--only', nargs = '+', choices = list(OUTPUTS), default = list(OUTPUTS))
    p.add_argument('--copy', dest = 'copy', action = 'store_true', default = True,
                   help = 'copy into writing/Paper (the default)')
    p.add_argument('--no-copy', dest = 'copy', action = 'store_false',
                   help = 'write results/paper only, leaving writing/Paper untouched')
    p.add_argument('--list', action = 'store_true', help = 'report buildability and exit')
    a = p.parse_args()

    built, skipped, report = [], [], []
    for name in a.only:
        kind, fn, rel = OUTPUTS[name]
        if a.list:
            try:
                fn()                      # cheap; the loaders raise before any real work
                print('{:<22} {:<7} OK'.format(name, kind))
            except D.MissingInput as e:
                print('{:<22} {:<7} BLOCKED -- {}'.format(name, kind, e))
            continue
        try:
            paths, rel = build(name, a.copy, report)
            built.append((name, rel, paths))
            print('built  {:<22} -> {}'.format(name, rel if a.copy else
                                               os.path.relpath(paths[0], C.REPO)))
        except D.MissingInput as e:
            skipped.append((name, str(e)))
            print('SKIP   {:<22} {}'.format(name, e))

    if a.list:
        return
    for line in report:
        print(line)
    print('\n{} built, {} skipped{}.'.format(len(built), len(skipped),
                                             '' if a.copy else ' (not copied: --no-copy)'))
    if skipped:
        print('Run the missing experiments with one of:')
        print('  .venv\\Scripts\\python.exe python\\paper\\runShocks.py      (Argentina)')
        print('  .venv\\Scripts\\python.exe python\\paper\\runShocksUS.py    (US / France / UK)')
        print('...and if a calibration is what is missing, the matching runCalibration*.py first.')
        for name, why in skipped:
            print('  {:<22} {}'.format(name, why))


if __name__ == '__main__':
    main()
