r""" Table builders. Each returns the complete tex body of one file in writing/Paper/Tables/.

The generated tex reproduces the STRUCTURE of the hand-written table it replaces (threeparttable,
booktabs rules, the same caption, label and notes), so the paper's \ref{}s keep resolving and a diff
against the previous version shows moved numbers rather than a re-layout. Only the numbers come from
results/.
"""
import numpy as np, pandas as pd

import config as C
import datasets as D

BANNER = ('%% GENERATED by python/paper/build.py from results/ -- do not edit by hand.\n'
          '%% Rebuild:  .venv\\Scripts\\python.exe python\\paper\\build.py --only {name}\n'
          '%% Source:   {src}\n')

LQ, RQ = '``', "''"      # tex quotation marks, kept out of the string literals below

# The one savings-rate convention of every table in the paper, Argentina and US alike: the unit, and
# what a non-baseline cell is. Levels are for baselines and calibration tables only.
SRNOTE = (r' The savings rate is savings relative to GDP; the baseline row reports its level and every '
          r'other row the change against that baseline in percentage points.')


def _wrap(name, src, caption, label, colspec, header, rows, note):
    """ One threeparttable. `rows` is a list of already-formatted cell lists. """
    body = '\n'.join(' & '.join(r) + r' \\[1ex]' for r in rows)
    return (BANNER.format(name = name, src = src)
            + '\\begin{table}[!htb]\n\\centering\n\\begin{threeparttable}\n'
            + '\\caption{' + caption + '}\n\\label{' + label + '}\n'
            + '\\begin{tabular}{' + colspec + '}\n\\toprule\n'
            + ' & '.join(header) + ' \\\\\n\\midrule \n'
            + body + '\n\\bottomrule\n\\end{tabular}\n'
            + '\\begin{tablenotes}\n\\footnotesize\n\\item ' + note
            + '\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n')


# ---------------------------------------------------------------------------------------------------
def argentinaCalibration():
    r""" Table \ref{table:Arg:Calib}: the calibrated and fixed parameters, with the target each one is
    identified by. Rows follow the paper's own order, with eta_0/X_0 appended -- they are calibrated
    jointly with beta/omega but the hand-written table omitted them. """
    c = D.calibrationSummary()
    ν = np.asarray(c['ν'], dtype = float)
    nDated = len(C.calendar()['dates'])   # the tail is the steady-state pad and has no calendar meaning
    rows = [
        [r'$\epsilon$ (\textit{pre}-reform)', '$' + C.num(c['ε']) + '$', 'Minimum-to-full pension coverage'],
        [r'$\theta$',   '$' + C.num(c['θ']) + '$', 'Replacement rate dispersion'],
        [r'$\alpha$',   '$' + C.num(c['α']) + '$', 'Factor income shares'],
        [r'$\nu_t$',    '$' + C.vec([ν[0], ν[nDated-1]], 2) + '$', '30-year gross population growth rates'],
        [r'$\xi$',      '$' + C.num(c['ξ']) + '$', 'Elasticity of labor supply'],
        [r'$\beta$',    '$' + C.num(c['β']) + '$', 'Capital--output ratio of $' + C.num(c['KY'], 2) + '$'],
        [r'$X_i$',      '$' + C.vec(c['Xi'], 2) + '$', 'Relative working hours'],
        [r'$\eta_i$',   '$' + C.vec(c['ηi'], 2) + '$', 'Income distribution'],
        [r'$\gamma_0$', '$' + C.num(c['γ0']) + '$', 'Recipients of basic pension'],
        [r'$\omega$',   '$' + C.num(c['ω']) + '$', 'Social security tax of $' + C.pct(c['τ'], 1) + '$'],
        [r'$\eta_0$',   '$' + C.num(c['η0'], 3) + '$',
         r'Informal relative income, eq.\ \eqref{eq:calibration_eta}'],
        [r'$X_0$',      '$' + C.num(c['X0'], 3) + '$', 'Informal relative working hours'],
    ]
    note = r'\textit{Note:} Our default specification relies on $\rho=' + C.num(c['ρ'], 0) + r'$.'
    return _wrap('ArgentinaCalibration', 'results/paper/calibrationSummary.csv',
                 'Calibration, Argentina', 'table:Arg:Calib', 'lll',
                 [r'\textbf{Parameter}', r'\textbf{Value}', r'\textbf{Target}'], rows, note)


# ---------------------------------------------------------------------------------------------------
def argentinaUniversal():
    r""" Table \ref{table:Argentina:Universal}: the reform decomposed into its economic-equilibrium and
    politico-economic parts, at the calibration year.

    The middle row is the point of the table -- taxes held at the baseline path, so its savings-rate
    response is the pure equilibrium effect, which runs opposite to the full effect. """
    ρ    = C.ARG['ρBaseline']
    ee   = D.shockPath(ρ, 'ee').iloc[0]
    ref  = D.shockPath(ρ, 'reform').iloc[0]
    year = C.calendar()['year0']

    srBase = D.savingsRatePath(ρ, 'base').iloc[0]
    srEE   = D.savingsRatePath(ρ, 'ee').iloc[0]
    srRef  = D.reformSavingsRate(ρ, 0)
    hRef   = D.baselineHours(ρ)     # the calibrated 2010 hours: 42.54 by definition, see config

    rows = [['Baseline',             C.pct(ee['τ_base']),    C.pct(srBase),         C.num(C.workweekHours(ee['h_base'], hRef))],
            ['Economic Equilibrium', C.pct(ee['τ_ee']),      C.pp(srEE - srBase),   C.num(C.workweekHours(ee['h_ee'], hRef))],
            ['Full effect',          C.pct(ref['τ_reform']), C.pp(srRef - srBase),  C.num(C.workweekHours(ref['h_reform'], hRef))]]
    note = (r'\textit{Note:} The reform permanently shifts $\epsilon = 1-\theta + \theta \eta_1 h_1/h$ '
            r'at the calibration year, unanticipated. The ' + LQ + 'Economic Equilibrium' + RQ +
            r' scenario solves for the new economic equilibrium path with taxes as in the Baseline '
            r'scenario, but with the new permanent $\epsilon$; the ' + LQ + 'Full effect' + RQ +
            r' scenario lets taxes be determined by the politico-economic equilibrium. $\rho=' +
            C.num(ρ, 0) + r"$." + SRNOTE + r" Aggregate hours have no "
            r"scale in the model, so the workweek is normalised to the observed average of "
            + C.num(C.calendar()['workweek']) + r" hours in the baseline.")
    return _wrap('ArgentinaUniversal', 'results/shocks/{eeOnly,universal}_match_rho%.4f.csv' % ρ,
                 'Pension system reform, year %d.' % year, 'table:Argentina:Universal', 'lccc',
                 [r'\textbf{Scenario}', r'\textbf{Tax rate}', r'\textbf{Savings rate}',
                  r'\textbf{Avg. workweek (hours)}'], rows, note)


# ---------------------------------------------------------------------------------------------------

def argentinaFuncOfRho(printAll = False):
    r""" Table \ref{table:Argentina:funcOfRho}: one shared pre-reform row, then the post-reform outcome
    at each rho -- tau and the workweek as levels, the savings rate as the change against THAT rho's own
    pre-reform level in p.p.

    The shared pre-reform row prints only what is common across the grid by construction: tau is a
    calibration target and the workweek is a normalisation. The pre-reform savings rate is neither --
    beta is identified by K/Y (eq:calibration:KY), so the 2010 savings rate s_t/Y_t is a prediction that
    varies with rho (15.3% at rho=0.5, 14.1% at rho=2) -- and its cell is therefore `--`, not the rho=1
    level. Each post-reform change is still differenced against its own rho's baseline path (the same
    quantity figure ARG_CRRA_LOG differences against); differencing against a single level misstated
    the effect at every other rho.

    Rows outside config.ARG['rhoTable'] are emitted COMMENTED rather than dropped, which is how the
    hand-written table carried them: the whole solved grid stays visible to whoever edits the paper
    without lengthening the printed table. printAll prints every row instead. """
    df = D.shockAtPeriod(0, 'reform')
    year = C.calendar()['year0']
    ww = C.calendar()['workweek']

    # The shared row is only legitimate if tau_base really is common: it is a target, so a spread across
    # rho means a calibration point missed it and the table must not paper over that.
    τBase = np.asarray(df['τ_base'], dtype = float)
    if np.ptp(τBase) > 1e-6:
        raise ValueError('pre-reform tau differs across rho (spread %.2e); it is a calibration target' % np.ptp(τBase))
    # The pre-reform workweek is the reference point itself, so it is the observed average exactly.
    rows = [['Pre-reform', C.pct(τBase[0]), '--', C.num(ww)]]
    for _, r in df.iterrows():
        ρ = r['ρ']
        srBase = D.savingsRatePath(ρ, 'base').iloc[0]
        post = [r'Post-reform, $\rho$ = ' + C.num(ρ, 1), C.pct(r['τ_reform']),
                C.pp(D.reformSavingsRate(ρ, 0) - srBase),
                C.num(C.workweekHours(r['h_reform'], D.baselineHours(ρ)))]
        show = printAll or any(np.isclose(ρ, v) for v in C.ARG['ρTable'])
        rows.append(post if show else ['% ' + post[0]] + post[1:])
    note = (r'\textit{Note:} The reform permanently shifts $\epsilon = 1-\theta + \theta \eta_1 h_1/h$. '
            r'Each $\rho$ is separately recalibrated to the same pre-reform targets, so the pre-reform '
            r'tax rate and workweek are common to every $\rho$. The savings rate is savings relative to '
            r'GDP; its pre-reform level is not targeted (the capital--output ratio is) and varies with '
            r'$\rho$, so each post-reform row reports the change against its own $\rho$' + "'" + r's '
            r'pre-reform level in percentage points. Aggregate hours have no scale in the model, so the '
            r'workweek is normalised to the observed average of ' + C.num(ww)
            + r' hours in each calibrated baseline. Commented rows are the remaining points of the '
            r'solved grid.')
    return _wrap('Argentina_funcOfRho', 'results/shocks/universal_match_rho*.csv',
                 r'Pension system reform, year %d, function of $\rho$' % year,
                 'table:Argentina:funcOfRho', 'lccc',
                 [r'\textbf{Scenario}', r'\textbf{Tax rate}', r'\textbf{Change in savings rate}',
                  r'\textbf{Avg. workweek (hours)}'], rows, note)
