// GENERATED by python/paper/onlineAppendix.py from python/paper/figures.py -- do not edit by hand.
export const STYLE = {
 "series": [
  "#2a78d6",
  "#eb6834"
 ],
 "ink": {
  "primary": "#0b0b0b",
  "secondary": "#52514e",
  "muted": "#898781",
  "grid": "#e1e0d9"
 },
 "rhoColours": [
  "#2a78d6",
  "#eb6834",
  "#52514e"
 ]
};
